name: Matrix Test

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: "Checkout code on ${{ matrix.os }}"
        uses: actions/checkout@v4

      - name: "Setup Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run tests
        run: |
          echo "Running tests with Node ${{ matrix.node-version }} on ${{ matrix.os }}"